name: 05 - Terraform Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/05-terraform.yml"

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_resource_group_name: "koalatech-week08-rg"
          TF_VAR_acr_name: "shaasweek0869826"
          TF_VAR_storage_account_name: "shaasweek0869826"
          TF_VAR_aks_cluster_name: "shaas-week08-aks"
          TF_VAR_aks_dns_prefix: "koalatech"
          TF_VAR_aks_node_count: "2"
          TF_VAR_aks_node_vm_size: "Standard_D2s_v5"
          TF_VAR_environment: "development"
        run: terraform plan -input=false